version: '3'

services:
  app:
    build: .
    environment:
      - PORT=3001
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=blogdb
      - TYPEORM_SYNC=true
      - JWT_EXPIRES_IN=7d
      - JWT_SECRET=32ehiubfgvdf734hr0340rf3rif93yvfh834f0823f9h82vf38
    depends_on:
      - db
    ports:
      - '3001:3001'
  db:
    image: postgres
    ports:
      - '35000:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=blogdb
