version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:1234@db/db
    ports:
      - 3000:3000
    depends_on:
      - db
